# Check the Discovery documents provided by Okta.
# https://YOUR_OKTA_DOMAIN/oauth2/default/.well-known/openid-configuration

okta_domain=integrator-4351893.okta.com
okta_authorize_uri=/oauth2/default/v1/authorize
okta_token_uri=/oauth2/default/v1/token
